version: '3.8'

services:
    cassandra:
        container_name: cassandra
        image: cassandra:latest
        ports:
            - "9042:9042"

    elasticsearch:
        container_name: elasticsearch
        image: elasticsearch:7.7.0
        ports:
            - "9200:9200"
            - "9300:9300"
        environment:
            discovery.type: single-node

    kibana:
        depends_on:
            - elasticsearch
        container_name: kibana
        image: kibana:7.7.0
        ports:
            - "5601:5601"