version: '3.8'

services:
    elasticsearch:
        container_name: elasticsearch
        image: elasticsearch:7.7.0
        ports:
            - "9200:9200"
            - "9300:9300"
        environment:
            discovery.type: single-node

    kibana:
        depends_on:
            - elasticsearch
        container_name: kibana
        image: kibana:7.7.0
        ports:
            - "5601:5601"

    mongo:
        image: mongo
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: admin
            MONGO_INITDB_ROOT_PASSWORD: admin
        ports:
            - "27017:27017"

    constructionla:
        build: .
        restart: always
        ports:
            - "5000:80"
        environment:
            MongoDB_Host: mongo
        depends_on:
            - mongo
            - kibana